spring:
  profiles:
    active: dev
  application:
    name: Inventory
  data:
    mongodb:
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      authentication-database: ${MONGODB_AUTH_SOURCE}
  thymeleaf:
    mode: HTML

homepage:
  title: ${TITLE}
